### ISSUE TITLE
JWT autentifikacija i autorizacija

### ISSUE THREAD

**Issue by EmmanuelF07** [vdavid033/iooa-2024-aukcije-2#10]

**Comment by MateoFeltrin** [comment]
Dodana JWT autentifikacija na (valjda) sve requestove gdje treba, POTREBNO TESTIRATI, staviti uvjete na gumbove i odjava da ima vizualni odgovor.

**Comment by MateoFeltrin** [comment]
Testirano, stavljeni uvjeti na gumbove i odjava ima vizualni odgovor i na admin dashboard dodan gumb za odjavu koji prije nije postojao
