### ISSUE TITLE
Nakon dodavanja aukcije, gumb nazad vodi na nepostojeću stranicu

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2024-aukcije-2#19]
Nakon dodavanja predmeta na aukciju -> na stranici http://localhost:8080/postavi
klikne se na gumb Natrag 
učitava se http://localhost:8080/IndexPage - javlja se greška 404

**Comment by Crytonics** [comment]
Riješeno u commits: https://github.com/vdavid033/iooa-2024-aukcije-2/commit/f50ec797e3354c04b7436b7b72941f19828ee8ea, https://github.com/vdavid033/iooa-2024-aukcije-2/commit/33998a89327a88d6cdf00377c685fd7b00bf2774

- Maknut gumb "Natrag"
- Kada je predmet spremljen, redirecta korisnika na taj predmet
- Gumb "Otkaži" sada radi i redirecta korisnika na početnu stranicu
