### ISSUE TITLE
Postavljanje cijene i vremena aukcije

### ISSUE THREAD

**Issue by tino1103** [vdavid033/iooa-2024-aukcije-2#22]

**Comment by tino1103** [comment]
Treba postavit da se početna cijena aukcije ne može staviti u minus i da vrijeme i završetaka aukcije bude tako da ne može završiti prije nego je počela aukcija. Popraviti da se vrijeme aukcije može promijeniti pomoću onog grafickog kruga. Za početak aukcije to radi ali za zavrsetak ne. Kada se odabere nis se ne promijeni.

**Comment by Crytonics** [comment]
Za postavljenje cijene ispravljeno u commitu: https://github.com/vdavid033/iooa-2024-aukcije-2/commit/897e969a2b454ebd1df3078ff0c449a4eae252b0.
A ispravak postavljanje završno vrijeme je ispravljeno u https://github.com/vdavid033/iooa-2024-aukcije-2/commit/d9fa5d818d56d54c6df654d120de9cefd9b3a36b.
