### ISSUE TITLE
Dodavanje datoteka koje nisu slike

### ISSUE THREAD

**Issue by tino1103** [vdavid033/iooa-2024-aukcije-2#24]
Moguće dodati word datoteku ili druge slične kao sliku. To bi trebalo postaviti da se može dodavati samo slike.

**Comment by Crytonics** [comment]
Ispravljeno u commitu: https://github.com/vdavid033/iooa-2024-aukcije-2/commit/99a299a42ebc0f51b96c4d21d32231a37b357751.
