### ISSUE TITLE
Pretraživanje aukcija

### ISSUE THREAD

**Issue by MateoFeltrin** [vdavid033/iooa-2024-aukcije-2#3]

**Comment by Crytonics** [comment]
Commit: https://github.com/vdavid033/iooa-2024-aukcije-2/commit/6fa767e68e0a1f823da64bab96372dad94acf460
Riješeno, spremno za push.

- [x] Stavljeno na Početnoj stranici gdje su sve aukcije
- [x] Stavljeno po kategorijama

```
- Izbrisane nepotrebne stavke sa Main Layout-a
- Dodano petraživanje na početnoj stranici
- Dodano petraživanje i unutar kategorija
```
