### ISSUE TITLE
Objava aukcija (predmeta)

### ISSUE THREAD

**Issue by MateoFeltrin** [vdavid033/iooa-2024-aukcije-2#4]

**Comment by Crytonics** [comment]
Objava aukcija/predmeta (1 dio)
Commit: https://github.com/vdavid033/iooa-2024-aukcije-2/commit/70c1ef3809a3b81a5cc3307eeb5b0be7720e70b9, https://github.com/vdavid033/iooa-2024-aukcije-2/commit/04eaf2ca3be8324634f500d580329e952bfd0d18, https://github.com/vdavid033/iooa-2024-aukcije-2/commit/50fc4608d46c95193c83d58acfdbdf37bc6b431c, https://github.com/vdavid033/iooa-2024-aukcije-2/commit/b32f18401553270fc1bd11a6f03aa02a509992ec, https://github.com/vdavid033/iooa-2024-aukcije-2/commit/febf1bd748c8ebff2ceb663b10495c8b673b6ea8

```
- Maknute nepotrebne stavke
- Uređen kod
- Preimenovane neke stavke
- Napravljeno da dohvati id aukcije za slike

- Za korisnike i kategorije se sada vuče iz baze te stavlja u padajući izbornik (u buduće će se maknut padajući izbornik za korisnike jer će se odvijati preko sesije)
- Unos slika i dalje ne radi (Unos ostalih podataka radi)

- Ispravljen odabir i unos datuma aukcije/predmeta
- Dodana restrikcija i obavijest ako korisnik nije odabrao sliku
- Za import datoteke je stavljeno da prima samo format od slika

- Sada se može ubacivat više slika za aukciju/predmet
- Ispravljen prikaz slika za aukciju/predmet
- Dodan novi modul za slike

- Maknuta opcija za odabir korisnika jer se sad se korisnika automatski prepozna kada je prijavljeen
- Dodana restrikcija da se može pristupit stranici samo ako je prijavljen
```

- [x] Unošenje korisnika u bazu preko tokena
- [x] Dopušten pristup samo prijavljenim korisnicima
- [x] Unos slika u bazu
- [x] Povezivanje aukcije (predmeta) id sa slikama
